### ISSUE TITLE
Feature: User can create an account/sign-in/sign-out

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/study-buddy-2#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account/sign-in/sign-out of the account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have the option to sign in/sign up using Clerk. If authenticated user will be redirected to "dashboard" screen, else user is directed to "home" page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to represent the home page
- [x] Create a component to represent a dashboard page
- [x] Install Clerk for authentication
- [x] create a middleware file to only allow the home page as public (for now)
- [x] Set up redirect with Clerk to move to dashboard on log in and home page on sign out
- [x] If user is already is signed in and clicks to sign in, redirect to dashboard
- [x] if user attempts to visit other pages and is not signed in, redirect to sign in
- [x] Create Navbar for home page that will direct to sign in, sign up, and resources pages
- [x] Create Navbar for authenticated pages with UserButton to allow profile "management" and sign out option

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
